---@diagnostic disable: undefined-global, lowercase-global
function AIRangeUpdated() end
function AddAmmo() end
function AddCargo() end
function AddInventory() end
function AddKnownItem() end
function AddLicence() end
function AddLogbookEntry() end
function AddMoney() end
function AddTradeToShipQueue() end
function AddUITriggeredEvent() end
function AddUnits() end
function AdjustMultilineString() end
function AttackEnemySettingChanged() end
function CalculateTotalHullFraction() end
function CanBeSubordinateOf() end
function CanTradeWith() end
function CanViewLiveData() end
function CancelConversation() end
function CheckInputProfileRegression() end
function CheckSuitableTransportType() end
function ClearContainerStockLimitOverride() end
function ClearContainerWarePriceOverride() end
function ClearLogbook() end
function ClearTradeQueue() end
function CompareJumpRoute() end
function ConvertIDTo64Bit() end
function ConvertIntegerString() end
function ConvertMissionLevelString() end
function ConvertMoneyString() end
function ConvertStringTo64Bit() end
function ConvertStringToLuaID() end
function ConvertTimeString() end
function CreateCutsceneDescriptor() end
function CreateInteractionDescriptor() end
function CreateObjectInPresentationCluster() end
function DestroyPresentationCluster() end
function ExistsText() end
function FindJumpRoute() end
function GetAccountData() end
function GetActiveGuidanceMissionComponent() end
function GetActiveMission() end
function GetAdapterOption() end
function GetAimAssistOption() end
function GetAllCommanders() end
function GetAllExtensionSettings() end
function GetAllStatIDs() end
function GetAllWeapons() end
function GetAmmoCountAfterTradeOrders() end
function GetAutoPilotTarget() end
function GetAutorollOption() end
function GetAutosaveOption() end
function GetBonusContentData() end
function GetBoostToggleOption() end
function GetBudgetData() end
function GetBuildAnchor() end
function GetBuildDuration() end
function GetBuildProductionMethod() end
function GetBuilderMacros() end
function GetCaptureHQOption() end
function GetCargoAfterTradeOrders() end
function GetCharacterDensityOption() end
function GetClusters() end
function GetCollectableData() end
function GetCollisionAvoidanceAssistOption() end
function GetCommander() end
function GetCommanderEntity() end
function GetComponentData() end
function GetComponentName() end
function GetConfineMouseOption() end
function GetContainedObjectsByOwner() end
function GetContainedShips() end
function GetContainedShipsByOwner() end
function GetContainedSpacesByOwner() end
function GetContainedStations() end
function GetContainedStationsByOwner() end
function GetContainerWarePrice() end
function GetContextByClass() end
function GetControlEntity() end
function GetControlPostData() end
function GetCrashReportOption() end
function GetCurRealTime() end
function GetCurTime() end
function GetDeadzoneOption() end
function GetDistortionOption() end
function GetEffectDistanceOption() end
function GetEfficiencyUpgrades() end
function GetEntityTypeData() end
function GetExtensionList() end
function GetExtensionUpdateWarningText() end
function GetFOVOption() end
function GetFactionData() end
function GetFreeCargoAfterTradeOrders() end
function GetFreeUnitStorageAfterTradeOrders() end
function GetFullscreenOption() end
function GetGamepadModeOption() end
function GetGammaOption() end
function GetGates() end
function GetGfxQualityOption() end
function GetGlobalSyncSetting() end
function GetGlowOption() end
function GetHeldLicences() end
function GetHintPosition() end
function GetHoloMapColors() end
function GetInputActionMap() end
function GetInputProfiles() end
function GetInputRangeMap() end
function GetInputStateMap() end
function GetInventory() end
function GetInversionSetting() end
function GetJoysticksOption() end
function GetLODOption() end
function GetLegacyShadersOption() end
function GetLibrary() end
function unknown() end
function GetLibrarySize() end
function GetLocalizedKeyName() end
function GetLocalizedRawKeyName() end
function GetLogbook() end
function GetMacroData() end
function GetMacroUnitStorageCapacity() end
function GetMappedJoysticks() end
function GetMaxTextLength() end
function GetMenuParameters() end
function GetMiningUnitMacros() end
function GetMissionDetails() end
function GetMissionObjective() end
function GetMissionOfferAtConnection() end
function GetMissionOfferDetails() end
function GetModuleType() end
function GetMouseLookToggleOption() end
function GetNPCBlackboard() end
function GetNPCs() end
function GetNPCsInSectorOnStations() end
function GetNumAffordableTradeItems() end
function GetNumLogbook() end
function GetNumMissions() end
function GetOrderParams() end
function GetOwnLicences() end
function GetPeopleRoleData() end
function GetPersonalizedCrashReportsOption() end
function GetPlatforms() end
function GetPlayerActivity() end
function GetPlayerContextByClass() end
function GetPlayerInventory() end
function GetPlayerMoney() end
function GetPlayerRoom() end
function GetPlayerTarget() end
function GetPossibleAdapters() end
function GetPossibleProducts() end
function GetPossibleResolutions() end
function GetPrioritizedPlatformNPCs() end
function GetProductionModuleData() end
function GetProductionModules() end
function GetRadarModuleName() end
function GetRadarOption() end
function GetReferenceProfit() end
function GetRegisteredModules() end
function GetResolutionOption() end
function GetRumbleOption() end
function GetSSAOOption() end
function GetSaveList() end
function GetSectors() end
function GetSensitivitySetting() end
function GetShaderQualityOption() end
function GetShadowOption() end
function GetSoftShadowsOption() end
function GetSoundOption() end
function GetStandardUnitMacros() end
function GetStatData() end
function GetSteeringNoteOption() end
function GetStopShipInMenuOption() end
function GetStorageData() end
function GetSubordinates() end
function GetSubtitleOption() end
function GetTotalValue() end
function GetTradeData() end
function GetTradeList() end
function GetTradeOrders() end
function GetTradeRestrictions() end
function GetTradeShipData() end
function GetTradeShipList() end
function GetTradesAtConnection() end
function GetTrafficDensityOption() end
function GetTransportUnitMacros() end
function GetUIRelation() end
function GetUnitStorageData() end
function GetVersionString() end
function GetVolumeOption() end
function GetWareCapacity() end
function GetWareData() end
function GetWareExchangeTradeList() end
function GetWareProductionLimit() end
function HasAllResourcesToCraft() end
function HasContainerStockLimitOverride() end
function HasContainerWarePriceOverride() end
function HasLicence() end
function HasShipyard() end
function HasTag() end
function HaveExtensionSettingsChanged() end
function IncStatValue() end
function InstallSteamDLC() end
function InterruptPlayerComputer() end
function IsCheatVersion() end
function IsComponentClass() end
function IsComponentConstruction() end
function IsComponentOperational() end
function IsContainerOperationalRangeSufficient() end
function IsDockingPossible() end
function IsFactionKnown() end
function IsGamepadActive() end
function IsInfoUnlockedForPlayer() end
function IsKnownItem() end
function IsLuaDebugInputEnabled() end
function IsMacroClass() end
function IsPlayerFirstPerson() end
function IsSameComponent() end
function IsSameTrade() end
function IsSavingPossible() end
function IsSteamworksEnabled() end
function IsValidComponent() end
function IsWareIllegalTo() end
function ListenForInput() end
function LoadGame() end
function LoadInputProfile() end
function MakeRepairPriority() end
function NewGame() end
function OpenSteamOverlayStorePage() end
function OpenSteamOverlayWebPage() end
function OpenWorkshop() end
function Pause() end
function PlayCredits() end
function ProceedFromMenu() end
function QuitGame() end
function QuitModule() end
function ReadLuaDebugInput() end
function ReadText() end
function RemoveAmmo() end
function RemoveCargo() end
function RemoveInventory() end
function RemoveLogbookEntry() end
function RemoveOrderListParam() end
function RepairDestructibles() end
function ResetAllExtensionSettings() end
function RestoreGameOptions() end
function RestoreGraphicOptions() end
function RestoreSoundOptions() end
function ReturnFromMenu() end
function RoundTotalTradePrice() end
function SaveFullscreenOption() end
function SaveGame() end
function SaveInputProfile() end
function SaveInputSettings() end
function SaveResolutionOption() end
function ScheduleReloadUI() end
function SelectBackOption() end
function SetAdapterOption() end
function SetAimAssistOption() end
function SetAutorollOption() end
function SetAutosaveOption() end
function SetBoostToggleOption() end
function SetCaptureHQOption() end
function SetCharacterDensityOption() end
function SetCollisionAvoidanceAssistOption() end
function SetComponentName() end
function SetConfineMouseOption() end
function SetContainerStockLimitOverride() end
function SetContainerWarePriceOverride() end
function SetCrashReportOption() end
function SetDeadzoneOption() end
function SetDistortionOption() end
function SetEffectDistanceOption() end
function SetExtensionSettings() end
function SetFOVOption() end
function SetFullscreenOption() end
function SetGamepadModeOption() end
function SetGammaOption() end
function SetGfxQualityOption() end
function SetGlowOption() end
function SetInversionSetting() end
function SetJoysticksOption() end
function SetLODOption() end
function SetLegacyShadersOption() end
function SetMaxBudget() end
function SetMinBudget() end
function SetMouseLookToggleOption() end
function SetMouseSleeping() end
function SetNPCBlackboard() end
function SetNPCSkill() end
function SetOrderParam() end
function SetPersonalizedCrashReportsOption() end
function SetRadarOption() end
function SetResolutionOption() end
function SetRumbleOption() end
function SetSSAOOption() end
function SetSensitivitySetting() end
function SetShaderQualityOption() end
function SetShadowOption() end
function SetSoftShadowsOption() end
function SetSoundOption() end
function SetStatValue() end
function SetSteeringNoteOption() end
function SetStopShipInMenuOption() end
function SetSubtitleOption() end
function SetTrafficDensityOption() end
function SetVirtualCargoMode() end
function SetVolumeOption() end
function SignalObject() end
function StartAutoPilot() end
function StartConversationFromMenu() end
function StartSubConversationFromMenu() end
function StopAutoPilot() end
function ToggleFactionTradeRestriction() end
function ToggleFactionTradeWareOverride() end
function TransferInventoryToPlayer() end
function TransferMoneyToPlayer() end
function TransferPlayerInventoryTo() end
function TransferPlayerMoneyTo() end
function TruncateText() end
function UninstallSteamDLC() end
function Unpause() end
