---@diagnostic disable: undefined-global, lowercase-global

function __call() end
function __index() end
function __newindex() end
function abortScan() end
function activateAdditionalIcon() end
function activateAimTargetElement() end
function activateBar() end
function activateBar2() end
function activateCollectable() end
function activateCommanderElement() end
function activateCompass() end
function activateCrosshair() end
function activateDebugLine() end
function activateDebugOutline() end
function activateDronePanel() end
function activateDroneType() end
function activateFactionLadder() end
function activateFill() end
function activateHullShield() end
function activateIcon() end
function activateIconElements() end
function activateInteractElement() end
function activateMessageTickerBar() end
function activateMessageTickerText() end
function activateMissileIncoming() end
function activateMissileLock() end
function activateMissionArrow() end
function activateMonitor() end
function activateOutline() end
function activateOverlay() end
function activateOxygenBar() end
function activatePlayerShieldbar() end
function activateProgressbar() end
function activatePromo() end
function activateRadarPicking() end
function activateRectangleElements() end
function activateSeparateRadar() end
function activateSeta() end
function activateSofttarget() end
function activateState() end
function activateTargetArrow() end
function activateTargetIndicator() end
function activateTargetMonitorRadar() end
function activateTargetRectangle() end
function activateWeaponPanel() end
function activationScan() end
function active() end
function addDebugMessage() end
function AddGlobalAccess() end
function bgColor() end
function calculateHalfMaxHorizontalScreenExtents() end
function calculateHalfMaxVerticalScreenExtents() end
function calculateTargetPriority() end
function callback() end
function CallEventScripts() end
function CallHotkeyScripts() end
function CallTabScrollScripts() end
function CallUpdateScripts() end
function CallWidgetEventScripts() end
function cameraDistanceSorter() end
function canMessageBeSofttarget() end
function changePendingSofttarget() end
function changePriorityMissionTarget() end
function changeState() end
function checkMessageTickerActivation() end
function checkPendingSofttargetChange() end
function checkRadarActivation() end
function checkSofttargetChange() end
function clearDataOnVersionChange() end
function clickDialogButton() end
function closeCurrentState() end
function closeMenu() end
function collapseHandler() end
function color() end
function colorDroneType() end
function connectTargetElement() end
function constructPlaceholderText() end
function constructTargetElementData() end
function convertHorizontalAlignment() end
function convertVerticalAlignment() end
function createAxisPropertyInfo() end
function createDescriptors() end
function createFrameTexturePropertyInfo() end
function createHotkeyPropertyInfo() end
function createIconPropertyInfo() end
function createOverlayPropertyInfo() end
function createSink() end
function createTargetElement() end
function createTargetSystemClones() end
function createTextPropertyInfo() end
function data() end
function deactivateAdditionalIcon() end
function deactivateAimTargetElement() end
function deactivateBar() end
function deactivateBar2() end
function deactivateBottomText() end
function deactivateCollectable() end
function deactivateCommanderElement() end
function deactivateCompass() end
function deactivateCrosshair() end
function deactivateCutscene() end
function deactivateDebugLine() end
function deactivateDebugOutline() end
function deactivateDronePanel() end
function deactivateDroneType() end
function deactivateFactionLadder() end
function deactivateFill() end
function deactivateHullShield() end
function deactivateIcon() end
function deactivateIconElements() end
function deactivateInteractElement() end
function deactivateInteraction() end
function deactivateMessageTickerLine() end
function deactivateMissileIncoming() end
function deactivateMissileLock() end
function deactivateMissileLocks() end
function deactivateMissionArrow() end
function deactivateMonitor() end
function deactivateOffScreenBox() end
function deactivateOutline() end
function deactivateOverlay() end
function deactivateOxygenBar() end
function deactivatePlayerShieldbar() end
function deactivateProgressbar() end
function deactivatePromo() end
function deactivateRadarPicking() end
function deactivateRectangleElements() end
function deactivateSeparateRadar() end
function deactivateSeta() end
function deactivateSideText() end
function deactivateSideText2() end
function deactivateSofttarget() end
function deactivateState() end
function deactivateTargetArrow() end
function deactivateTargetIndicator() end
function deactivateTargetMonitorNotification() end
function deactivateTargetMonitorRadar() end
function deactivateTargetRectangle() end
function deactivateWeaponPanel() end
function deg2rad() end
function disableDroneTypeInteractions() end
function disconnectElement() end
function display() end
function displayAimTargetElement() end
function displayInactiveMissionLine() end
function displayMissionBar() end
function displayMissionDetails() end
function displayOption() end
function duration() end
function emms() end
function enableDroneTypeInteractions() end
function enableRadar() end
function enableSeparateRadar() end
function expandHandler() end
function f16() end
function finalizeFlowchartCellSlots() end
function finalizeTableColumnWidths() end
function finishScan() end
function flush() end
function fofs() end
function formatValue() end
function fp() end
function get() end
function getAimAtTargetIndicatorPosition() end
function getCameraDistanceBasedParameterValue() end
function getCellHeight() end
function getComponentHUDIcon() end
function getComponentIcon() end
function getCounterMeasurePosition() end
function getCurrentCrosshairMessage() end
function getCurrentType() end
function getDebugMessage() end
function getDistanceText() end
function getIconSize() end
function getLEDColor() end
function GetLiveData() end
function getMinTargetDelay() end
function getOverlayCellData() end
function getPOIIcon() end
function getPointerID() end
function getRectanglePositions() end
function getSectionBaseParam() end
function getShipOrLaserTowerSize() end
function getSquareDistanceToCenter() end
function getTargetConeRatio() end
function getTargetElementByMessageID() end
function getTargetElementByTargetSystem() end
function getTargetElementPosition() end
function getTargetElementScale() end
function getTargetIcon() end
function GetTargetMonitorDetails() end
function getTargetMonitorDetailsBridge() end
function getTargetPriority() end
function getTextChunks() end
function getUIElementScreenPosition() end
function handleMouseClick() end
function handleMouseClickRadar() end
function handleMouseDown() end
function handleMouseDownRadar() end
function hasActions() end
function hasPossibleActions() end
function hasVisibleActions() end
function hideAimTargetElement() end
function hideBar() end
function hideCells() end
function hideCompass() end
function hideDebugLine() end
function hideDebugLog() end
function hideDebugOutline() end
function hideDialogMenu() end
function hideEnvironmentInfo() end
function hideFPSCounter() end
function hideMissionDetails() end
function hideMouseOverText() end
function hideNotorietyBar() end
function hideOverlay() end
function hidePromo() end
function hideSkipNote() end
function hideSofttarget() end
function hideTargetMonitorNotification() end
function highlightColor() end
function info() end
function infotext() end
function init() end
function initButtonList() end
function initCells() end
function initDebugLogData() end
function initDronePanel() end
function initDynamicTargetElementData() end
function initEnvironmentObjectSupport() end
function initIcon() end
function initMissionBarScale() end
function initMousePicking() end
function initNotifications() end
function initNotorietyData() end
function initPlayerHullShield() end
function initPointerPicking() end
function initProverb() end
function initRadarPicking() end
function initScale() end
function initSeta() end
function initTableCell() end
function initTargetElement() end
function initVRTexts() end
function initWeaponPanel() end
function isBlinkingLED() end
function isCrosshairTarget() end
function isCurrentAimTargetElementActive() end
function isDebugLogActive() end
function isFirstPersonMode() end
function isHighestState() end
function isIconPropertyFunctionCell() end
function isInactiveTargetElementState() end
function isInTargetCone() end
function isInWeaponRange() end
function isObstructed() end
function isSeparateRadarEnabled() end
function isShipPOI() end
function isSmallShip() end
function isSomethingToDisplay() end
function isTargetable() end
function isTargetElementPendingDeletion() end
function isTargetMonitorRadarEnabled() end
function isTextPropertyFunctionCell() end
function isValidTargetMonitorDetailsBridgeData() end
function leaveDialogMenu() end
function lerpColorModeColor() end
function listOptions() end
function MakeGlobalAvailable() end
function makeTargetElementKnown() end
function mouseOverText() end
function name() end
function neg_selectable() end
function negative() end
function nop() end
function normalizeAngle() end
function onActiveWeaponGroupChanged() end
function onButtonSelectDown() end
function onButtonSelectLeft() end
function onButtonSelectRight() end
function onButtonSelectUp() end
function onChangedEnvironmentObject() end
function onChatRead() end
function onChatReceived() end
function onChatUpdateHandler() end
function onCheckUsername() end
function onClear() end
function onConversationFinished() end
function onConversationStarted() end
function onCopy() end
function onCutsceneReady() end
function onCutsceneStopped() end
function onDebugLog() end
function onDebugLogViewCreated() end
function onDialog1MouseClick() end
function onDialog1MouseOver() end
function onDialog1POVOver() end
function onDialog2MouseClick() end
function onDialog2MouseOver() end
function onDialog2POVOver() end
function onDialog3MouseClick() end
function onDialog3MouseOver() end
function onDialog3POVOver() end
function onDialog4MouseClick() end
function onDialog4MouseOver() end
function onDialog4POVOver() end
function onDialog5MouseClick() end
function onDialog5MouseOver() end
function onDialog5POVOver() end
function onDialog6MouseClick() end
function onDialog6MouseOver() end
function onDialog6POVOver() end
function onDroneClick() end
function onDroneModeClick() end
function onDroneModeOut() end
function onDroneModeOver() end
function onDroneOut() end
function onDroneOver() end
function onEnableMouseOverText() end
function onEnableRadar() end
function onEnableSeparateRadar() end
function onEnterDialogMenu() end
function onExternalTargetView() end
function onExternalTargetViewActive() end
function onExternalTargetViewInactive() end
function onFirstButton() end
function onFlightControlStarted() end
function onFlightControlStopped() end
function onFrameCounterViewCreated() end
function onFrameHandleViewCreated() end
function onGamePaused() end
function onGamePlanChange() end
function onGameUnpaused() end
function onHideCompass() end
function onHideDebugLine() end
function onHideDebugLog() end
function onHideFPS() end
function onHideFPSCounter() end
function onHideInfoBar() end
function onHidePromo() end
function onHotkey() end
function onIncomingMail() end
function onInputModeChanged() end
function onInteractionHidden() end
function onInteractionShown() end
function onInventoryWaresAdded() end
function onLastButton() end
function onLeaveDialogMenu() end
function onLoadingDone() end
function onMailRead() end
function onMissileIncoming() end
function onMissileLockInitiated() end
function onMissileLockLost() end
function onMissionInfoUpdate() end
function onMissionObjectiveBarUpdate() end
function onMissionPosIDConnected() end
function onMissionPosIDDisconnected() end
function onMouseClick() end
function onMouseClickMessageTickerChatNotification() end
function onMouseClickMessageTickerFooter() end
function onMouseClickMessageTickerNotification() end
function onMouseClickMessageTickerRow1() end
function onMouseClickTargetMonitor() end
function onMouseDown() end
function onMouseOut() end
function onMouseOver() end
function onMouseUp() end
function onNextButton() end
function onNotificationFreed() end
function onNumMissionsChanged() end
function onPlatformFriendsLookedUp() end
function onPlayerActivityChanged() end
function onPrevButton() end
function onPriorityMissiontargetChanged() end
function onReceiveContacts() end
function onReducedSpeedModeActivated() end
function onReducedSpeedModeDeactivated() end
function onReenable() end
function onRefreshTargetMonitor() end
function onResetHUDColors() end
function onScanAborted() end
function onScanFinished() end
function onScanStarted() end
function onSetaActivated() end
function onSetaDeactivated() end
function onShowCompass() end
function onShowDebugLine() end
function onShowGameOver() end
function onShowInfoBar() end
function onShowNotification() end
function onShowPromo() end
function onSkipScreenshot() end
function onSofttargetChanged() end
function onStartDialog() end
function onStopDialog() end
function onTeleportSucceeded() end
function onTickerOnlyMode() end
function onToggleAssert() end
function onToggleAssertPopUp() end
function onToggleErrorPopUp() end
function onToggleOptionalAssert() end
function onToggleOptionalAssertPopUp() end
function onToggleRadarMode() end
function onToggleShowFPSButton() end
function onTurretClick() end
function onTurretModeClick() end
function onTurretModeOut() end
function onTurretModeOver() end
function onTurretOut() end
function onTurretOver() end
function onUnlock() end
function onUpdate() end
function onUpdateColorMap() end
function onUpdateHandler() end
function onUpdateHUDColors() end
function onVoiceOutput() end
function onVRPointerChanged() end
function onWeaponGroupChanged() end
function opc2() end
function opc3() end
function performSelectSofttargetOnClick() end
function pos_selectable() end
function positive() end
function precacheScreenshots() end
function prefixicon() end
function prepareLiveUpdateText() end
function processConnectionList() end
function processEnterInteractMenuEvent() end
function processInteractionDescriptor() end
function processLiveUpdateValues() end
function processMessageTickerNotifications() end
function processOverlay() end
function processSofttargetChange() end
function queueNotification() end
function ReadText() end
function RegisterEvent() end
function registerMouseButton() end
function removeAllPointerOverrides() end
function removeAutoLock() end
function removeFill() end
function removeOldestMessage() end
function removeOutline() end
function RemoveScript() end
function removeSofttargetLockRequest() end
function removeStateRequest() end
function requestSofttargetLock() end
function requestState() end
function resetElement() end
function resetScheduledShowDialogMenu() end
function resetTargetSystem() end
function resolutionsort() end
function resultfunc() end
function rex() end
function scaleFont() end
function scheduleAutoLock() end
function scheduleShowDialogMenu() end
function script() end
function selectable() end
function selectDialogButton() end
function set() end
function setAutoCrosshairTargetSelection() end
function setBarState() end
function setBottomText() end
function setCellOpacities() end
function setCellOpacity() end
function setCentralElementsPosition() end
function setCheckedText() end
function setColoredText() end
function setColorHelper() end
function setDecoColors() end
function setDecoColorsWithIntensity() end
function setDialogButtonColor() end
function setDisplayMode() end
function SetEGOGlobals() end
function setElementColorAlpha() end
function setElementTextColor() end
function setExternalFirstPersonMode() end
function setFirstPersonAutoTargeting() end
function setFirstPersonMode() end
function setGamepadMode() end
function setHintText() end
function setIconPos() end
function setJoystickMode() end
function setMissileLockColor() end
function setMissileLockState() end
function setMouseMode() end
function setMouseOverPosition() end
function setMouseOverTextEnabled() end
function setMultilineLeftRightText() end
function setObstructionBasedColor() end
function setPercentage() end
function setPointerOverride() end
function setPosition() end
function setProgressText() end
function SetScript() end
function setShipMode() end
function setSideText() end
function setSideText2() end
function setSpaceMode() end
function setTableColumnWidthData() end
function setTargetElementColor() end
function setTextColor() end
function setTextElement() end
function setTextLine() end
function setTextWithLineBreaks() end
function setTouchControllerMode() end
function setTurretColor() end
function setTurretMode() end
function setWeaponColor() end
function shouldDisplayNotorietyBar() end
function showBar() end
function showCell() end
function showCompass() end
function showDebugLine() end
function showDebugLog() end
function showDebugOutline() end
function showDialogMenu() end
function showEnvironmentInfo() end
function showFill() end
function showFPSCounter() end
function showGameOver() end
function showMouseOverText() end
function showNotification() end
function showNotorietyBar() end
function showOutline() end
function showOverlay() end
function showPromo() end
function showSkipNote() end
function showSofttarget() end
function sliderHandler() end
function sortDebugLog() end
function sorter() end
function startScan() end
function startSofttargetInteraction() end
function statusText() end
function switchButton() end
function switchScreenshot() end
function switchTargetMonitorNotification() end
function sz() end
function test1() end
function test2() end
function toggleDebugLog() end
function toggleRadarMode() end
function ToReprString() end
function truncateLeftRightText() end
function unmapDialogButton() end
function UnregisterEvent() end
function unselectDialogButton() end
function unselectMouseJoystickButton() end
function unsetPointerOverride() end
function updateActiveState() end
function updateActivityColor() end
function updateAimTargetElement() end
function updateAllOutlines() end
function updateAllPointerOverrides() end
function updateArrowState() end
function updateBoostBar() end
function updateBottomText() end
function updateButtons() end
function updateChatNotification() end
function updateCheckEngineLight() end
function updateColor() end
function updateControllerSelection() end
function updateCountermeasures() end
function updateCoverLine() end
function updateDebugMessage() end
function updateDebugOutlines() end
function updateDialogMenuButtons() end
function updateDronePanel() end
function updateDroneType() end
function updateDynamicRectangleIcons() end
function updateElementPosition() end
function updateFPS() end
function updateHullShield() end
function updateIcon() end
function updateIconSize() end
function updateIndicators() end
function updateIndicatorScalePositionAndActivation() end
function updateInteractiveText() end
function updateMailNotification() end
function updateMatchSpeedElement() end
function updateMessages() end
function updateMessageStartTimes() end
function updateMessageTicker() end
function updateMissileLock() end
function updateMissileLockColor() end
function updateMissileLocks() end
function updateMissionArrow() end
function updateMissionDetails() end
function updateMousePosition() end
function updateMouseSteeringLine() end
function updateNotorietyLadder() end
function updateOffScreenBox() end
function updateOutline() end
function updateOxygenBar() end
function updatePointerOverride() end
function updateProgressbar() end
function updateRadar() end
function updateRadarExtents() end
function updateRadarTarget() end
function updateRectangleElements() end
function updateReenableButton() end
function updateRelation() end
function updateRelationStatusData() end
function updateScenarioTexts() end
function updateScreenshots() end
function updateSelectedButton() end
function updateSelection() end
function updateSeta() end
function updateSideText() end
function updateSideText2() end
function updateSideTextPosition() end
function updateSofttargetLock() end
function updateSofttargetManager() end
function updateSofttargetManagerActivationState() end
function updateSofttargetTargetElement() end
function updateSpeedbar() end
function updateState() end
function updateStates() end
function updateTargetArrow() end
function updateTargetElement() end
function updateTargetElementData() end
function updateTargetElementPosition() end
function updateTargetMonitorDisplay() end
function updateTargetMonitorNotifications() end
function updateTargetText() end
function updateText() end
function updateVelocityIndicator() end
function updateWeaponGroup() end
function updateWeaponPanel() end
function upgradeData() end
function value() end
function vex() end
function vm() end
function warning() end
